jwt:
  secret: hello.world.ee.ff
  redis:
    #    host: redis
    host: localhost
    port: 6379

---
server:
  port: 8080
  http:
    port: 80

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hack.cn9h0errreou.ap-northeast-2.rds.amazonaws.com:3306/hackathon_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: mung
    password: hhs2684021

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  #        default_batch_fetch_size: 100

---
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.web.cors: DEBUG
